<section class="faq-section">
    <h1 class="first-heading">TERMS OF SERVICE</h1>
<p>LAST REVISION: [10-08-2022]</p>

<p>PLEASE READ THIS TERMS OF SERVICE AGREEMENT CAREFULLY. BY USING THIS WEBSITE OR ORDERING PRODUCTS OR SERVICES FROM THIS WEBSITE YOU AGREE TO BE BOUND BY ALL OF THE TERMS AND CONDITIONS OF THIS AGREEMENT.</p>

<p>This Terms of Service Agreement (the &quot;Agreement&quot;) governs your use of this website, [https://think-champ.com/] (the &quot;Website&quot;),&nbsp;<strong>Think Champ</strong>&nbsp;offer services and products for purchase on this Website, or your purchase of products available on this Website. This Agreement includes, and incorporates by this reference, the policies and guidelines referenced below.&nbsp;<strong>Think Champ</strong>&nbsp;reserves the right to change or revise the terms and conditions of this Agreement at any time by posting any changes or a revised Agreement on this Website.&nbsp;<strong>Think Champ</strong>&nbsp;will alert you that changes or revisions have been made by indicating on the top of this Agreement the date it was last revised. The changed or revised Agreement will be effective immediately after it is posted on this Website. Your use of the Website following the posting any such changes or of a revised Agreement will constitute your acceptance of any such changes or revisions.&nbsp;<strong>Think Champ</strong>&nbsp;encourages you to review this Agreement whenever you visit the Website to make sure that you understand the terms and conditions governing use of the Website. This Agreement does not alter in any way the terms or conditions of any other written agreement you may have with&nbsp;<strong>Think Champ</strong>&nbsp;for other products or services. If you do not agree to this Agreement (including any referenced policies or guidelines), please immediately terminate your use of the Website.</p>

<p><strong>I. PRODUCTS</strong></p>

<p>Terms of Offer. This Website offers for sale certain products (the &quot;Products&quot;). By placing an order for Products through this Website, you agree to the terms set forth in this Agreement.</p>

<p><strong>Customer Solicitation:</strong>&nbsp;Unless you notify our third party call center reps or direct&nbsp;<strong>Think Champ</strong>&nbsp;sales reps, while they are calling you, of your desire to opt out from further direct company communications and solicitations, you are agreeing to continue to receive further emails and call solicitations&nbsp;<strong>Think Champ</strong>&nbsp;and its designated in house or third party call team(s).</p>

<p><strong>Opt Out Procedure:</strong>&nbsp;We provide 3 easy ways to opt out of from future solicitations. 1. You may use the opt out link found in any email solicitation that you may receive. 2. You may also choose to opt out, via sending your email address to:&nbsp;info@hoss.co.in</p>

<p>3. You may send a written remove request to. B - 6 / 60 GF Safdarjung Enclave, New Delhi - 110029</p>

<p><strong>Proprietary Rights</strong>&nbsp;:&nbsp;<strong>Think Champ</strong>&nbsp;has proprietary rights and trade secrets in the Products. You may not copy, reproduce, resell or redistribute any Product manufactured and/or distributed by<strong>Think Champ.</strong>&nbsp;<strong>Think Champ</strong>&nbsp;also has rights to all trademarks and trade dress and specific layouts of this webpage, including calls to action, text placement, images and other information.</p>

<p><strong>Goods and Sales Tax</strong>&nbsp;: If you purchase any Products, you will be responsible for paying any applicable sales tax.</p>

<p><strong>II. WEBSITE</strong></p>

<p><strong>Content;</strong>&nbsp;<strong>Intellectual Property; Third Party Links</strong>&nbsp;. In addition to making Products available, this Website also offers information and marketing materials. This Website also offers information, both directly and through indirect links to third-party websites.&nbsp;<strong>Think Champ</strong>&nbsp;does not always create the information offered on this Website; instead the information is often gathered from other sources. To the extent that&nbsp;<strong>Think Champ</strong>&nbsp;does create the content on this Website, such content is protected by intellectual property laws of the India, foreign nations, and international bodies. Unauthorized use of the material may violate copyright, trademark, and/or other laws. You acknowledge that your use of the content on this Website is for personal, noncommercial use. Any links to third-party websites are provided solely as a convenience to you.&nbsp;<strong>Think Champ</strong>&nbsp;does not endorse the contents on any such third-party websites.&nbsp;<strong>Think Champ</strong>&nbsp;is not responsible for the content of or any damage that may result from your access to or reliance on these third-party websites. If you link to third-party websites, you do so at your own risk.</p>

<p><strong>Use of Website</strong>&nbsp;;&nbsp;<strong>Think Champ</strong>&nbsp;is not responsible for any damages resulting from use of this website by anyone. You will not use the Website for illegal purposes. You will (1) abide by all applicable local, state, national, and international laws and regulations in your use of the Website (including laws regarding intellectual property), (2) not interfere with or disrupt the use and enjoyment of the Website by other users, (3) not resell material on the Website, (4) not engage, directly or indirectly, in transmission of &quot;spam&quot;, chain letters, junk mail or any other type of unsolicited communication, and (5) not defame, harass, abuse, or disrupt other users of the Website</p>

<p><strong>License;</strong>&nbsp;By using this Website, you are granted a limited, non-exclusive, non-transferable right to use the content and materials on the Website in connection with your normal, noncommercial, use of the Website. You may not copy, reproduce, transmit, distribute, or create derivative works of such content or information without express written authorization from&nbsp;<strong>Think Champ</strong>&nbsp;or the applicable third party (if third party content is at issue).</p>

<p><strong>Posting</strong>&nbsp;; By posting, storing, or transmitting any content on the Website, you hereby grant&nbsp;<strong>Think Champ</strong>&nbsp;a perpetual, worldwide, non-exclusive, royalty-free, assignable, right and license to use, copy, display, perform, create derivative works from, distribute, have distributed, transmit and assign such content in any form, in all media now known or hereinafter created, anywhere in the world. You are solely responsible for your interactions with other users of the Website and any content you post.&nbsp;<strong>Think Champ</strong>&nbsp;is not liable for any damage or harm resulting from any posts by or interactions between users.&nbsp;<strong>Think Champ</strong>&nbsp;reserves the right, but has no obligation, to monitor interactions between and among users of the Website and to remove any content&nbsp;<strong>Think Champ</strong>&nbsp;deems objectionable, in&nbsp;<strong>Think Champ</strong>&nbsp;sole discretion.</p>

<p><strong>III. DISCLAIMER OF WARRANTIES</strong></p>

<p>Your use of this website and/or products are at your sole risk. The website and products are offered on an &quot;as is&quot; and &quot;as available&quot; basis.&nbsp;<strong>Think Champ</strong>&nbsp;expressly disclaims all warranties of any kind, whether express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose and non-infringement with respect to the products or website content, or any reliance upon or use of the website content or products or services. (&quot;products&quot; include trial products.)</p>

<p>Without limiting the generality of the foregoing,&nbsp;<strong>Think Champ</strong>&nbsp;makes no warranty:</p>

<p>That the information provided on this website is accurate, reliable, complete, or timely,</p>

<p>That the links to third-party websites are to information that is accurate, reliable, complete, or timely.</p>

<p>No advice or information, whether oral or written, obtained by you from this website will create any warranty not expressly stated herein. As to the results that may be obtained from the use of the products or that defects in products will be corrected regarding any products purchased or obtained through the website.</p>

<p><strong>IV. LIMITATION OF LIABILITY</strong></p>

<p><strong>Think Champ</strong>&nbsp;entire liability, and your exclusive remedy, in law, in equity, or otherwise, with respect to the website content and products and/or for any breach of this agreement is solely limited to the amount you paid, less taxes, for products or services purchased via the website.</p>

<p><strong>Think Champ</strong>&nbsp;will not be liable for any direct, indirect, incidental, special or consequential damages in connection with this agreement or the products in any manner, including liabilities resulting from (1) the use or the inability to use the website content or products; (2) the cost of procuring substitute products or content; (3) any products purchased or obtained or transactions entered into through the website; or (4) any lost profits you allege.</p>

<p><strong>V. INDEMNIFICATION</strong></p>

<p>You will release, indemnify, defend and hold harmless&nbsp;<strong>Think Champ</strong>, and any of its contractors, agents, employees, officers, directors, shareholders, affiliates and assigns from all liabilities, claims, damages, costs and expenses, including reasonable attorneys&#39; fees and expenses, of third parties relating to or arising out of (1) this Agreement or the breach of your warranties, representations and obligations under this Agreement; (2) the Website content or your use of the Website content; (3) the Products or your use of the Products (including Trial Products); (4) any intellectual property or other proprietary right of any person or entity; (5) your violation of any provision of this Agreement; or (6) any information or data you supplied to<strong>Think Champ</strong>&nbsp;When&nbsp;<strong>Think Champ</strong>&nbsp;is threatened with suit or sued by a third party,&nbsp;<strong>Think Champ</strong>&nbsp;may seek written assurances from you concerning your promise to indemnify&nbsp;<strong>Think Champ</strong>; your failure to provide such assurances may be considered by&nbsp;<strong>Think Champ</strong>&nbsp;to be a material breach of this Agreement.&nbsp;<strong>Think Champ</strong>&nbsp;will have the right to participate in any defense by you of a third-party claim related to your use of any of the Website content or Products, with counsel of<strong>&nbsp;Think Champ</strong>&nbsp;choice at its expense.&nbsp;<strong>Think Champ</strong>&nbsp;will reasonably cooperate in any defense by you of a third-party claim at your request and expense. You will have sole responsibility to defend&nbsp;<strong>Think Champ</strong>&nbsp;against any claim, but you must receive&nbsp;<strong>Think Champ</strong>&nbsp;prior written consent regarding any related settlement. The terms of this provision will survive any termination or cancellation of this Agreement or your use of the Website or Products or services.</p>

<p><strong>VI. PRIVACY</strong></p>

<p><strong>Think Champ</strong>&nbsp;believes strongly in protecting user privacy. Please refer to&nbsp;<strong>Think Champ</strong>&nbsp;privacy policy, incorporated by reference herein, that is posted on the Website.</p>

<p><strong>VI. AGREEMENT TO BE BOUND</strong></p>

<p>By using this Website or ordering Products or using services, you acknowledge that you have read and agree to be bound by this Agreement and all terms and conditions on this Website.</p>

<p><strong>VIII. GENERAL</strong></p>

<p><strong>Force Majeure</strong>&nbsp;.&nbsp;<strong>Think Champ</strong>&nbsp;will not be deemed in default hereunder or held responsible for any cessation, interruption or delay in the performance of its obligations hereunder due to earthquake, flood, fire, storm, natural disaster, act of God, war, terrorism, armed conflict, labor strike, lockout, or boycott.</p>

<p><strong>Cessation of Operation</strong>&nbsp;.&nbsp;<strong>Think Champ</strong>&nbsp;may at any time, in its sole discretion and without advance notice to you, cease operation of the Website and distribution of the Products.</p>

<p><strong>Entire Agreement</strong>&nbsp;. This Agreement comprises the entire agreement between you and&nbsp;<strong>Think Champ</strong>&nbsp;and supersedes any prior agreements pertaining to the subject matter contained herein.</p>

<p><strong>Effect of Waiver</strong>&nbsp;. The failure of&nbsp;<strong>Think Champ</strong>&nbsp;to exercise or enforce any right or provision of this Agreement will not constitute a waiver of such right or provision. If any provision of this Agreement is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties&#39; intentions as reflected in the provision, and the other provisions of this Agreement remain in full force and effect.</p>

<p><strong>Governing Law;</strong>&nbsp;This Website originates from the Delhi, India. This Agreement will be governed by the laws of the State of Delhi, India without regard to its conflict of law principles to the contrary. Neither you nor&nbsp;<strong>Think Champ</strong>&nbsp;will commence or prosecute any suit, proceeding or claim to enforce the provisions of this Agreement, to recover damages for breach of or default of this Agreement, or otherwise arising under or by reason of this Agreement, other than in courts located in State of Delhi, India. By using this Website or ordering Products, you consent to the jurisdiction and venue of such courts in connection with any action, suit, proceeding or claim arising under or by reason of this Agreement. You hereby waive any right to trial by jury arising out of this Agreement and any related documents.</p>

<p><strong>Statute of Limitation</strong>&nbsp;. You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of the Website or Products or this Agreement must be filed within one (1) year after such claim or cause of action arose or be forever barred.</p>

<p><strong>Teachers:</strong>&nbsp;If you are a Teacher, you understand and agree that your relationship with&nbsp;<strong>Think Champ</strong>&nbsp;is limited to being a Member and an independent, third-party contractor, and not an employee, agent, joint- venturer or partner of&nbsp;<strong>Think Champ</strong>&nbsp;for any reason, and you act exclusively on your own behalf and for your own benefit, and not on behalf of or for the benefit of<strong>&nbsp;Think Champ</strong>.&nbsp;<strong>Think Champ</strong>&nbsp;does not control, your offline activities. As a Member you agree not to do anything to create a false impression that you are endorsed by, partnering with, or acting on behalf of or for the benefit of&nbsp;<strong>Think Champ</strong>, including by inappropriately using any&nbsp;<strong>Think Champ</strong>&nbsp;intellectual property.</p>

<p><strong>Posting</strong>&nbsp;; By posting, storing, or transmitting any content on the Website, you hereby grant&nbsp;<strong>Think Champ</strong>&nbsp;a perpetual, worldwide, non-exclusive, royalty-free, assignable, right and license to use, copy, display, perform, create derivative works from, distribute, have distributed, transmit and assign such content in any form, in all media now known or hereinafter created, anywhere in the world. You are solely responsible for your interactions with other users of the Website and any content you post.&nbsp;<strong>Think Champ</strong>&nbsp;is not liable for any damage or harm resulting from any posts by or interactions between users.&nbsp;<strong>Think Champ</strong>&nbsp;reserves the right, but has no obligation, to monitor interactions between and among users of the Website and to remove any content&nbsp;<strong>Think Champ</strong>&nbsp;deems objectionable, in&nbsp;<strong>Think Champ</strong>&nbsp;sole discretion.</p>

<p><strong>Waiver of Class Action Rights</strong>&nbsp;. By Entering Into This Agreement, You Hereby Irrevocably Waive Any Right You May Have To Join Claims With Those Of Other In The Form Of A Class Action Or Similar Procedural Device. Any Claims Arising Out Of, Relating To, Or Connection with This Agreement Must Be Asserted Individually.</p>

<p><strong>Termination.</strong>&nbsp;<strong>Think Champ</strong>&nbsp;reserves the right to terminate your access to the Website if it reasonably believes, in its sole discretion, that you have breached any of the terms and conditions of this Agreement. Following termination, you will not be permitted to use the Website and&nbsp;<strong>Think Champ</strong>&nbsp;may, in its sole discretion and without advance notice to you, cancel any outstanding orders for Products or services. If your access to the Website is terminated,&nbsp;<strong>Think Champ</strong>&nbsp;reserves the right to exercise whatever means it deems necessary to prevent unauthorized access of the Website. This Agreement will survive indefinitely unless and until&nbsp;<strong>Think Champ</strong>&nbsp;chooses, in its sole discretion and without advance to you, to terminate it.</p>

<p><strong>Domestic Use</strong>&nbsp;.&nbsp;<strong>Think Champ</strong>&nbsp;makes no representation that the Website or Products are appropriate or available for use in locations outside India. Users who access the Website from outside India do so at their own risk and initiative and must bear all responsibility for compliance with any applicable local laws.<br />
Assignment. You may not assign your rights and obligations under this Agreement to anyone.&nbsp;<strong>Think Champ</strong>&nbsp;may assign its rights and obligations under this Agreement in its sole discretion and without advance notice to you.</p>

<p>By using this website or ordering products from this website you agree<br />
to be bound by all of the terms and conditions of this agreement.</p>

</section>